site_name: Sport Ludique Chartres
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

plugins: 
  - drawio 
  - search
theme :
  icon :
    annotation : material/arrow-right-circle-outline
  logo : logo.png
  name : material
  language : fr
  palette:
    - scheme: default
      primary: red
      accent: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Introduction: index.md
  - Documentation Mkdocs:
      - Plugins: DocumentationMkdocs/Plugins/plugin.md
      - Syntaxe: DocumentationMkdocs/Syntaxe/Syntaxe.md
  - Switch Core:
      - Configuration du Switch Core & Stack : SWCore/reseau.md
      - LACP : SWCore/lacp_hp_a5500.md
  - Routeur:
      - R1: Routeur/R1.md
      - R2: Routeur/R2.md 
      - Protocoles:
          - HSRP: Routeur/hsrp.md
          - PAT: Routeur/PAT.md
  - Pare-feux:
      - Régle Pare-Feu: Pare-feux/réglePF.md
      - PFW: Pare-feux/stormshield.md
      - Proxy: Pare-feux/proxy.md
      - LDAPS - Liaison PFW & AD: Pare-feux/ldaps-pfw.md
      - VFW: Pare-feux/opnsense.md
      - UFW: Pare-feux/UFW.md
  - HyperViseur:
      - Proxmox & Raid: Hyperviseur/proxmox-raid.md
      - Gestion Vlan on VM Proxmox: Hyperviseur/vlan-prox.md
      - Protocoles: 
          - LACP on Proxmox: Hyperviseur/lacp-proxmox.md
          - LDAPS on Proxmox: Hyperviseur/ldaps-prox.md
  - Service Active Directory:
      - Incident Utilisateurs Active Directory: Service AD/incidents.md
      - Domaine Active Directory: Service AD/ad.md
      - Active Directory BackUP: Service AD/adbackup.md
      - Gestion Utilisateurs AD: Service AD/adusers.md
      - Liaison Proxmox & AD: Service AD/liaison-prox-ad.md
      - Cerficat ADCS & LDAPS: Service AD/adcs.md
      - Service Active Directory:
          - Serveur DNS (Actuellement Innactif): Service AD/dns.md
          - Serveur DHCP: Service AD/dhcp.md
          - Serveur Fichier: Service AD/servfichier.md
  - DNS:
      - DNS Autorité: DNS/DNS-autorité.md
      - DNS Resolveur: DNS/DNS Resolveur.md
  - Services: 
      - Serveurs : 
          - Base de Données: Services/bdd.md
          - Serveur web: Services/Web.md
          - GLPI: 
                - Installation GLPI: Services/Glpi.md
                - Liaison AD & GLPI via LDAP: Services/Glpi-ldap.md
                - Mise en place inventaire: Services/Glpi-inventaire.md
      - Sécurité:
          - Certificat SSL/TLS & HTTPS: Services/https.md
      - WordPress:
          - Installation WordPress: Services/wordpress.md
          - Configuration WordPress: Services/wordpress2.md
          - Configuration Multi Site WordPress: Services/wordpress3.md
      - Reverse Proxy: 
          - Configuration Reverse Proxy: Services/reverse-proxy.md
          - Reverse Proxy Secondaire: Services/reverse-proxy-secondaire.md
